### ISSUE TITLE
Set up grid defender plugin

### ISSUE THREAD

**Issue by Blaylock1988** [Blaylock1988/GVK-AlphaKharak-Settings#7]

**Comment by Blaylock1988** [comment]
Attempted with DePatch first. If doesnt work will need to add the Reborn Core and Reborn Defender plugins

**Comment by Blaylock1988** [comment]
![image](https://user-images.githubusercontent.com/62247634/142142934-2a9b31a3-cb93-4d65-a361-ef4849f903ae.png)

Need to test these impact speeds and damages against voxels and other grids

**Comment by AlphaMatte** [comment]
Grid vs grid ram tested at 90mps - no damage, slight glitching into grid

Grid vs Grid ram Tested at 70mps - no damage immediately but grids glitched into eachother causing low sim warning and low performance. One glitched together blocks started taking damage because they were below the speed threshhold. 

Grid vs grid ram tested at 50mps - no damage no glitching

Grid vs grid ram tested at 50mps part 2 - no damage initially but caused glitching into other grid then damage occured

Grid vs voxel ram test at 90mps - no damage to grid, yes damage to voxels

Grid vs voxel test at 50mps - no damage to grid, yes damage to voxel

**Comment by AlphaMatte** [comment]
Grid vs voxel ram test at 90mps - slight damage to grid, yes damage to voxel

**Comment by Blaylock1988** [comment]
Its supposed to allow damage to all grids if the speed is over 60m/s. Sounds like its not allowing that correctly. I'll switch it to the other plugin after work today.

**Comment by AlphaMatte** [comment]
yeah it was lodging itself into the other grid instead of bouncing off.

**Comment by Blaylock1988** [comment]
Switched to Reborn.Defender plugin
![image](https://user-images.githubusercontent.com/62247634/142351136-77b1ae72-dc91-41f4-8bed-123be7e4141f.png)

Large grids under 50 blocks and over 60m/s should cause damage to any grid
Small grids under 100 blocks and over 60m/s should cause damage to any grid
Originally this was made specifically to allow PMW missiles to impart damage while also preventing big ship ramming meta.

**Comment by Blaylock1988** [comment]
Working perfectly. Grids take damage when smashing into voxels at high speed as desired as well
